version: '3'
services:
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    environment:
#     - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
#      - character-set-server=utf8
#      - collation-server=utf8_bin
#      - default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-server/var/lib/mysql:/var/lib/mysql:rw
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.0-latest
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
    ports:
      - 10051:10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
      - ./zabbix-server/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zabbix-server/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zabbix-server/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - ./zabbix-server/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zabbix-server/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./zabbix-server/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zabbix-server/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    restart: always
    ulimits:
      nproc: 65535
    depends_on:
      - mysql-server

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
    container_name: zabbix-web-nginx-mysql
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zabbix-web/etc/ssl/nginx:/etc/ssl/nginx:ro
      - ./zabbix-web/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    restart: always
    ports:
      - 80:8080
    depends_on:
      - mysql-server